"""empty message

Revision ID: 003df09770e3
Revises: c32220a14144
Create Date: 2024-11-24 21:22:44.405354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '003df09770e3'
down_revision = 'c32220a14144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))

    # ### end Alembic commands ###
