"""empty message

Revision ID: 02ec754b693a
Revises: 96a62450cf1c
Create Date: 2024-11-25 09:08:54.153407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ec754b693a'
down_revision = '96a62450cf1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index('password', ['password'], unique=True)

    # ### end Alembic commands ###
