"""empty message

Revision ID: 0da2622d66ae
Revises: 3e145db33c92
Create Date: 2024-11-25 22:57:48.838762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da2622d66ae'
down_revision = '3e145db33c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_index('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_schedule', schema=None) as batch_op:
        batch_op.create_index('date', ['date'], unique=True)
        batch_op.drop_column('id')

    # ### end Alembic commands ###
