"""empty message

Revision ID: 5f41f45d6163
Revises: 24a022f16df9
Create Date: 2024-11-24 19:27:33.966589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f41f45d6163'
down_revision = '24a022f16df9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_schedule', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['exam_registration_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_schedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
