"""empty message

Revision ID: 71ae0c525d51
Revises: c544fd6a2ba4
Create Date: 2024-11-22 14:37:23.944417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ae0c525d51'
down_revision = 'c544fd6a2ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint('admin_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_constraint('doctor_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('nurse', schema=None) as batch_op:
        batch_op.drop_constraint('nurse_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint('patient_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.drop_constraint('phone_number_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'account', ['account_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_ibfk_1', 'account', ['account_id'], ['id'])

    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('phone_number_ibfk_1', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('patient_ibfk_1', 'user', ['id'], ['id'])

    with op.batch_alter_table('nurse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('nurse_ibfk_1', 'user', ['id'], ['id'])

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('doctor_ibfk_1', 'user', ['id'], ['id'])

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('admin_ibfk_1', 'user', ['id'], ['id'])

    # ### end Alembic commands ###
