"""empty message

Revision ID: dc2a17d24b92
Revises: 4a70d020692a
Create Date: 2024-11-26 11:15:22.901789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc2a17d24b92'
down_revision = '4a70d020692a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_schedule',
    sa.Column('exam_time_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_book', sa.Boolean(), nullable=False),
    sa.Column('exam_registration_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['exam_registration_id'], ['exam_registration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_time_id'], ['exam_time.id'], ),
    sa.PrimaryKeyConstraint('exam_time_id', 'doctor_id', 'date'),
    sa.UniqueConstraint('exam_registration_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_schedule')
    # ### end Alembic commands ###
