"""empty message

Revision ID: fdfbf179631c
Revises: 71ae0c525d51
Create Date: 2024-11-22 16:21:37.387678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdfbf179631c'
down_revision = '71ae0c525d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_registration', schema=None) as batch_op:
        batch_op.drop_column('exam_day')

    with op.batch_alter_table('exam_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_free', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('exam_registration_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'exam_registration', ['exam_registration_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_schedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('exam_registration_id')
        batch_op.drop_column('is_free')
        batch_op.drop_column('id')

    with op.batch_alter_table('exam_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_day', sa.DATE(), nullable=False))

    # ### end Alembic commands ###
